name: Deploy ARM Template and Function App

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
        template: ./arm-template.json
        parameters: >
          sourceStorageAccountName=${{ secrets.SOURCE_STORAGE_ACCOUNT_NAME }}
          destinationStorageAccountName=${{ secrets.DESTINATION_STORAGE_ACCOUNT_NAME }}
          mainQueueName=${{ secrets.MAIN_QUEUE_NAME }}
          functionAppName=${{ secrets.FUNCTION_APP_NAME }}
          slackWebhookUrl=${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Deploy Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.FUNCTION_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./upload_function

    env:
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}